Logging improvements
aws/aws-application-networking-k8s pull request #378
Opened 2023-08-31 20:17 UTC by xWink

**What type of PR is this?**

cleanup

**Which issue does this PR fix**:
#126 partially

**What does this PR do / Why do we need it**:
- Removes glog entirely
- All previous uses of glog are replaced with zap logger
- Tests that now must use an implementation of zap logger use the fallback logger
- Removal of redundant newlines in logs
- NO controller functionality changes or log content changes, this is only a change from glog to zap

**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**:

**Testing done on this change**:

N/A

**Automation added to e2e**:

N/A

**Will this PR introduce any new dependencies?**:

No

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No. N/A

**Does this PR introduce any user-facing change?**:

Logs will be a bit cleaner, but nothing else.

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-31 21:20 UTC, mikhail-aws requested changes
Reviewed half of it. Before going further few major comments.

1. Approach, lets agree on the that. I would expect if we touch code, we dont want to come back again for another logging improvement. So it's better to have a fewer but complete changes, than many and come back again. Why come back again, will list below.
2. glog.V6 is debug, there are many places where debug converted into info log.
3. glog.v2 is info, there are places where info converted into debug.
4. multi-line logging - merge into one
5. log error or return error, dont do both
6. statements with `foo,err := getFoo()`, and then we log both log.Info(foo, err), not good, if error happened and we handle it by logging, we do if err != nil { log(err) }
7. Info logging with %v - we talked about it - no %v, log only fields that we care about. Not sure which fields are important, log just name or id. For debugging can be used, carefully.

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_manager.go
> +	s.log.Infof("calling findListenerByNamePort serviceID %v port %d", serviceID, port)
I would use debug for all logs in this method

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_manager.go
> +	s.log.Debugf("Delete  listener resp %vm err :%v", resp, err)
another gift

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_synthesizer.go
>  			return errors.New(errmsg)
no log

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_synthesizer.go
> +	l.log.Infof("getSDKlistener: %v, err: %v", sdkListeners, err)
log error with if condition

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_synthesizer.go
> +		l.log.Infof("ListenerSynthesize >>>> delete staled sdk listener %v", *sdkListener)
glog.V(6) is Debug level.

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/listener_synthesizer.go
>  			return sdkListeners, errors.New("getSDKRules: failed to find service in store")
no log, should wrap error in return

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +	r.log.Debugf("resp: %v, err: %v", resp, err)
single log statement after err!=nil check

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +	r.log.Infof("Rule --- update >>>>>>>>.%v", rules)
debug

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
>  		return errors.New(errmsg)
no log

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
>  		return errors.New(errmsg)
no log

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +	r.log.Debugln(resp)
:(

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +		log.Infoln("Checking PathMatchExact")
debug and for friends below

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +	r.log.Infof("resp: %v, err: %v", resp, err)
single log after error hanlding

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
> +			r.log.Debugf("findMatchingRule, rule %v not found err:%v", ruleInput, err)
v2 is info, v6 is debug

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_manager.go
>  	return err
no log, should wrap error with details from this log

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_synthesizer.go
> +	r.log.Infof("Synthesize rule = %v, err :%v", resRule, err)
if err, then log error

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_synthesizer.go
>  			return err
no log on error return

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_synthesizer.go
> +	r.log.Infof("rule>>> synthesize,  sdkRules :%v err: %v", sdkRules, err)
if err, then log

2023-08-31 21:20 UTC, mikhail-aws commented on pkg/deploy/lattice/rule_synthesizer.go
>  		return modelRule, errors.New("rule not found")
no log

2023-08-31 21:56 UTC, solmonk commented
In addition - let's remove "#####" or ">>>>>" style logs whenever possible (sorry not sure how to call these)

This could be too much for one PR so we may just split the PR by components - (do controller, do manager, do modelbuild, and so on)

2023-08-31 21:59 UTC, solmonk commented
btw I'm totally happy with replacing a few info logs with debug logs by good judgement. I would like to see minimal set of logs when debug mode is off

2023-09-24 05:57 UTC, xWink commented
Going to close this and use it as reference for fresh, smaller PRs.

First one is up
https://github.com/aws/aws-application-networking-k8s/pull/410

2023-09-24 05:57 UTC, closed without merging